#+title: Continental

* intro

Web
System
Are you ready for an exciting and action-packed mission? Our intelligence will combine with your talent. We are closer than ever to the perpetrator of the attack on the international oil pipeline, nicknamed Crow.

It all started last week when 61-year-old Jefferson T., whose card had been cloned in recent months, noticed anomalous charges on his credit card. An investigation by law enforcement found evidence that the credit card had been used by Crow, the perpetrator of the attack on an international oil pipeline.

The last time we saw a charge on the credit card was from a hotel booking website. Crow must be staying at a hotel. We need you to get all the information you can about Crow's stay, such as the date of the stay, the room number. With your information, we'll set up an operation at the hotel where Crow is staying.

At the moment, the only thing we know about the accommodation is Crow's e-mail address: jtippin4y@unknownmail.com

I am sure you will find this email address very useful.

Good luck!

* initial scan
#+begin_src sh links
http://reservia.hv/js/aos.js
http://reservia.hv/css/style.css
https://fonts.googleapis.com/css?family=Alex+Brush
http://reservia.hv/js/bootstrap-datepicker.js
http://reservia.hv/js/jquery.magnific-popup.min.js
http://reservia.hv/blog/detail
http://reservia.hv/js/google-map.js
http://reservia.hv/js/
http://reservia.hv/js/scrollax.min.js
http://reservia.hv/hotels/90
http://reservia.hv/hotels/647f0d4da9108a79b01c63b3
http://reservia.hv/js/owl.carousel.min.js
http://reservia.hv/js/main.js
http://reservia.hv/css/aos.css
http://reservia.hv/css/owl.theme.default.min.css
http://reservia.hv/hotels/647f0d3ea9108a79b01c63b1
https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700
http://reservia.hv/about
http://reservia.hv/blog
https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false
http://reservia.hv/hotels/63
http://reservia.hv/css/icomoon.css
http://reservia.hv/js/jquery-migrate-3.0.1.min.js
http://reservia.hv/js/bootstrap.min.js
http://reservia.hv/css/owl.carousel.min.css
http://reservia.hv/contact
http://reservia.hv/
http://reservia.hv/css/flaticon.css
http://reservia.hv/js/jquery.min.js
http://reservia.hv/js/jquery.animateNumber.min.js
http://reservia.hv/js/jquery.waypoints.min.js
http://reservia.hv/css/animate.css
http://reservia.hv/css/jquery.timepicker.css
http://reservia.hv/hotels/647f0d82a9108a79b01c63b7
http://reservia.hv/js/jquery.stellar.min.js
http://reservia.hv/css/magnific-popup.css
http://reservia.hv/js/popper.min.js
http://reservia.hv/night
http://reservia.hv/images/airplane.ico
http://reservia.hv/hotels/647f0d73a9108a79b01c63b5
http://reservia.hv/css/ionicons.min.css
http://reservia.hv/js/jquery.timepicker.min.js
http://reservia.hv/hotels
http://reservia.hv/hotels/647f0d2ba9108a79b01c63af
http://reservia.hv/css/open-iconic-bootstrap.min.css
http://reservia.hv/hotels/647f0d90a9108a79b01c63b9
http://reservia.hv/css/bootstrap-datepicker.css
http://reservia.hv/hotels/40
http://reservia.hv/js/jquery.easing.1.3.js
#+end_src

*nmap* ->
#+begin_src sh
PORT      STATE SERVICE REASON         VERSION
22/tcp    open  ssh     syn-ack ttl 63 OpenSSH 8.4p1 Debian 5+deb11u1 (protocol
2.0)
80/tcp    open  http    syn-ack ttl 63 nginx 1.18.0
27017/tcp open  mongod? syn-ack ttl 63
#+end_src


jtippin4y@unknownmail.com

https://hackviser.com/tactics/pentesting/web/xxe
